checks:
  neutron_dpdk_enabled:
    requires:
      apt: openvswitch-switch-dpdk
  nova_libvirt_queue_sizes_invalid_config:
    requires:
      config:
        handler: hotsos.core.plugins.openstack.OpenstackConfig
        path: etc/nova/nova.conf
        invert-result: True
        assertions:
          rx_queue_size:
            section: libvirt
            ops: [[ge, 1024]]
            allow-unset: False
          tx_queue_size:
            section: libvirt
            ops: [[ge, 1024]]
            allow-unset: False
conclusions:
  nova-dpdk-config-not-valid:
    decision:
      and:
        - neutron_dpdk_enabled
        - nova_libvirt_queue_sizes_invalid_config
    raises:
      type: hotsos.core.issues.OpenstackWarning
      message: >-
        DPDK is enabled but rx_queue_size/tx_queue_size set incorrectly in
        nova.conf (expect both to be >= 1024).
