#!/usr/bin/python3
import re
import os

from common import helpers

# HOTSOS GLOBALS
VERBOSITY_LEVEL = int(os.environ.get('VERBOSITY_LEVEL', 0))
DATA_ROOT = os.environ.get('DATA_ROOT', '/')

info = {}


for type in ["bcache", "nvme"]:
    info[type] = {}
    for line in helpers.get_ls_lanR_sys_block():
        ret = re.compile(r".+[0-9:]+\s+({}[0-9a-z]+)\s+.+".format(type)
                         ).match(line)
        if ret:
            devname = ret[1]
            info[type][devname] = {}

            for line in helpers.get_udevadm_info_dev(devname):
                ret = re.compile(r".+\s+disk/by-dname/(.+)").match(line)
                if ret:
                    info[type][devname]["dname"] = ret[1]
                else:
                    # TODO: get backing dev
                    pass


if info:
    for type in info:
        print("  {}:".format(type))
        for dev in info[type]:
            print("    {}:".format(dev))
            for key in info[type][dev]:
                print("      {}: {}".format(key, info[type][dev][key]))
