#!/usr/bin/python3
import re
import os

from common import helpers

# HOTSOS GLOBALS
VERBOSITY_LEVEL = int(os.environ.get('VERBOSITY_LEVEL', 0))
DATA_ROOT = os.environ.get('DATA_ROOT', '/')

BCACHE_INFO = {}


def get_bcache_info():
    for type in ["bcache", "nvme"]:
        BCACHE_INFO[type] = {}
        for line in helpers.get_ls_lanR_sys_block():
            ret = re.compile(r".+[0-9:]+\s+({}[0-9a-z]+)\s+.+".format(type)
                             ).match(line)
            if ret:
                devname = ret[1]
                BCACHE_INFO[type][devname] = {}

                for line in helpers.get_udevadm_info_dev(devname):
                    ret = re.compile(r".+\s+disk/by-dname/(.+)").match(line)
                    if ret:
                        BCACHE_INFO[type][devname]["dname"] = ret[1]
                    else:
                        # TODO: get backing dev
                        pass


if __name__ == "__main__":
    get_bcache_info()
    if BCACHE_INFO:
        helpers.HOTSOSYaml.dump(BCACHE_INFO, indent=2)
