import os

from hotsos.core.config import HotSOSConfig
from hotsos.core.plugins.storage import ceph

from .. import utils


CEPH_MON_DATA_ROOT = os.path.join(utils.TESTS_DIR,
                                  'fake_data_root/storage/ceph-mon')

SNAP_LIST_MICROCEPH = """
Name       Version                Rev    Tracking       Publisher   Notes
core20     20240111               2182   latest/stable  canonical✓  base
core22     20240111               1122   latest/stable  canonical✓  base
lxd        5.0.3-9a1d904          27428  5.0/stable/…   canonical✓  -
microceph  18.2.0+snap450240f5dd  975    reef/stable    canonical✓  held
snapd      2.61.2                 21184  latest/stable  canonical✓  snapd
"""

CEPH_CONF = """
# # Generated by MicroCeph, DO NOT EDIT.
[global]
run dir = /var/snap/microceph/current/run
fsid = d219246a-6edc-4655-8c6d-2af0f38b1e0b
mon host = 192.168.122.111
public_network = 192.168.122.0/24
auth allow insecure global id reclaim = false
ms bind ipv4 = true
ms bind ipv6 = false
# https://tracker.ceph.com/issues/70390
bluestore_elastic_shared_blobs = false
"""


class CephCommonTestsBase(utils.BaseTestCase):
    """ Custom test case that sets the storage plugin context. """
    def setUp(self):
        super().setUp()
        HotSOSConfig.data_root = CEPH_MON_DATA_ROOT
        HotSOSConfig.plugin_name = 'storage'


class TestCephConfig(CephCommonTestsBase):
    """ Test for ceph config class """

    def test_config(self):
        conf = ceph.common.CephConfig()
        expected = ['auth cluster required',
                    'auth service required',
                    'auth client required',
                    'mon host',
                    'fsid',
                    'log to syslog',
                    'err to syslog',
                    'clog to syslog',
                    'mon cluster log to syslog',
                    'debug mon',
                    'debug osd',
                    'mon pg warn max object skew',
                    'public network',
                    'cluster network',
                    'public addr',
                    'cluster addr',
                    'keyring',
                    'mon data avail warn',
                    'mon data avail crit',
                    'keyring']

        self.assertEqual(conf.all_keys, expected)

    @utils.create_data_root(files_to_create={
        'var/snap/microceph/current/conf/ceph.conf': CEPH_CONF})
    def test_microceph_config(self):
        conf = ceph.common.CephConfig()
        expected = ['run dir',
                    'fsid',
                    'mon host',
                    'public_network',
                    'auth allow insecure global id reclaim',
                    'ms bind ipv4',
                    'ms bind ipv6',
                    'bluestore_elastic_shared_blobs']

        self.assertEqual(conf.all_keys, expected)


class TestCephPluginDeps(CephCommonTestsBase):
    """ Unit tests for ceph plugin deps. """
    def test_ceph_dep_dpkg(self):
        self.assertTrue(ceph.common.CephChecks().is_runnable())

    @utils.create_data_root({'sos_commands/snap/snap_list_--all':
                             SNAP_LIST_MICROCEPH})
    def test_ceph_dep_snap(self):
        self.assertTrue(ceph.common.CephChecks().is_runnable())
        self.assertEqual(ceph.common.CephChecks().release_name, 'reef')


@utils.load_templated_tests('scenarios/storage/ceph/common')
class TestCephCommonScenarios(CephCommonTestsBase):
    """
    Scenario tests can be written using YAML templates that are auto-loaded
    into this test runner. This is the recommended way to write tests for
    scenarios. It is however still possible to write the tests in Python if
    required. See https://hotsos.readthedocs.io/en/latest/contrib/testing.html
    for more information.
    """
