import os

from hotsos.core.config import HotSOSConfig
from hotsos.core.plugins.storage import ceph

from .. import utils


CEPH_MON_DATA_ROOT = os.path.join(utils.TESTS_DIR,
                                  'fake_data_root/storage/ceph-mon')

SNAP_LIST_MICROCEPH = """
Name       Version                Rev    Tracking       Publisher   Notes
core20     20240111               2182   latest/stable  canonical✓  base
core22     20240111               1122   latest/stable  canonical✓  base
lxd        5.0.3-9a1d904          27428  5.0/stable/…   canonical✓  -
microceph  18.2.0+snap450240f5dd  975    reef/stable    canonical✓  held
snapd      2.61.2                 21184  latest/stable  canonical✓  snapd
"""

CEPH_CONF = """
# # Generated by MicroCeph, DO NOT EDIT.
[global]
run dir = /var/snap/microceph/current/run
fsid = d219246a-6edc-4655-8c6d-2af0f38b1e0b
mon host = 192.168.122.111
public_network = 192.168.122.0/24
auth allow insecure global id reclaim = false
ms bind ipv4 = true
ms bind ipv6 = false
# https://tracker.ceph.com/issues/70390
bluestore_elastic_shared_blobs = false
"""


class CephCommonTestsBase(utils.BaseTestCase):
    """ Custom test case that sets the storage plugin context. """
    def setUp(self):
        super().setUp()
        HotSOSConfig.data_root = CEPH_MON_DATA_ROOT
        HotSOSConfig.plugin_name = 'storage'


class TestCephConfig(CephCommonTestsBase):
    """ Test for ceph config class """

    def test_config(self):
        """Test ceph config keys are parsed correctly."""
        conf = ceph.common.CephConfig()
        expected = ['auth cluster required',
                    'auth service required',
                    'auth client required',
                    'mon host',
                    'fsid',
                    'log to syslog',
                    'err to syslog',
                    'clog to syslog',
                    'mon cluster log to syslog',
                    'debug mon',
                    'debug osd',
                    'mon pg warn max object skew',
                    'public network',
                    'cluster network',
                    'public addr',
                    'cluster addr',
                    'keyring',
                    'mon data avail warn',
                    'mon data avail crit',
                    'keyring']

        self.assertEqual(conf.all_keys, expected)

    @utils.create_data_root(files_to_create={
        'var/snap/microceph/current/conf/ceph.conf': CEPH_CONF})
    def test_microceph_config(self):
        """Test microceph snap config keys are parsed."""
        conf = ceph.common.CephConfig()
        expected = ['run dir',
                    'fsid',
                    'mon host',
                    'public_network',
                    'auth allow insecure global id reclaim',
                    'ms bind ipv4',
                    'ms bind ipv6',
                    'bluestore_elastic_shared_blobs']

        self.assertEqual(conf.all_keys, expected)


class TestCephPluginDeps(CephCommonTestsBase):
    """ Unit tests for ceph plugin deps. """
    def test_ceph_dep_dpkg(self):
        """Test ceph is runnable via dpkg packages."""
        self.assertTrue(ceph.common.CephChecks().is_runnable())

    @utils.create_data_root({'sos_commands/snap/snap_list_--all':
                             SNAP_LIST_MICROCEPH})
    def test_ceph_dep_snap(self):
        """Test ceph is runnable via microceph snap."""
        self.assertTrue(ceph.common.CephChecks().is_runnable())
        self.assertEqual(ceph.common.CephChecks().release_name, 'reef')


class TestCephChecks(CephCommonTestsBase):
    """ Unit tests for ceph checks. """
    @utils.create_data_root(
        {'sos_commands/ceph_osd/'
         'ceph_daemon_.var.run.ceph.ceph-osd.0.asok_perf_dump': (
             '{"bluefs": {"db_total_bytes": 1073741824}}'),
         'sos_commands/ceph_osd/'
         'ceph_daemon_.var.run.ceph.ceph-osd.1.asok_perf_dump': (
             '{"bluefs": {"db_total_bytes": 10737418240}}'),
         'sos_commands/ceph_osd/ceph-volume_lvm_list': (
             '====== osd.0 =======\n'
             '  osd fsid                  test-osd-fsid-0\n'
             '  devices                   /dev/mapper/ceph-osd-0\n'
             '====== osd.1 =======\n'
             '  osd fsid                  test-osd-fsid-1\n'
             '  devices                   /dev/mapper/ceph-osd-1\n')})
    def test_local_osds_with_small_bluestore_db(self):
        """Test BlueStore DB devices at or below the minimum size are found."""
        checks = ceph.common.CephChecks()

        self.assertEqual(checks.local_osds_with_small_bluestore_db,
                         ['osd.0'])

    def test_mds_balancer_disabled_by_interval(self):
        """Test mds balancer disabled by interval."""
        cases = [
            ('mds config dump',
             [{'name': 'mds_bal_interval',
               'section': 'mds',
               'value': '0'}], {}, True),
            ('global config dump',
             [{'name': 'mds_bal_interval',
               'section': 'global',
               'value': '0'}], {}, True),
            ('mds overrides global',
             [{'name': 'mds_bal_interval',
               'section': 'global',
               'value': '0'},
              {'name': 'mds_bal_interval',
               'section': 'mds',
               'value': '10'}], {}, False),
            ('ceph config fallback', [], {'mds_bal_interval': '0'}, True),
        ]
        for name, config_dump, ceph_config, expected in cases:
            with self.subTest(name=name):
                checks = ceph.common.CephChecks()
                checks.cluster.ceph_config_dump = config_dump
                checks.cluster.crush_map.ceph_report = {}
                checks.ceph_config = ceph_config
                self.assertEqual(checks.mds_balancer_disabled, expected)

    def test_mds_balancer_disabled_by_balance_automate(self):
        """Test mds balancer disabled by balance_automate flag."""
        cases = [
            ('disabled for all filesystems',
             [{'mdsmap': {'flags_state': {'balance_automate': False}}},
              {'mdsmap': {'flags_state': {'balance_automate': False}}}],
             True),
            ('enabled for one filesystem',
             [{'mdsmap': {'flags_state': {'balance_automate': False}}},
              {'mdsmap': {'flags_state': {'balance_automate': True}}}],
             False),
            ('flag unavailable', [{'mdsmap': {}}], False),
        ]
        for name, filesystems, expected in cases:
            with self.subTest(name=name):
                checks = ceph.common.CephChecks()
                checks.cluster.ceph_config_dump = []
                checks.cluster.crush_map.ceph_report = {
                    'fsmap': {'filesystems': filesystems}}
                checks.ceph_config = {}
                self.assertEqual(checks.mds_balancer_disabled, expected)


@utils.load_templated_tests('scenarios/storage/ceph/common')
class TestCephCommonScenarios(CephCommonTestsBase):
    """
    Scenario tests can be written using YAML templates that are auto-loaded
    into this test runner. This is the recommended way to write tests for
    scenarios. It is however still possible to write the tests in Python if
    required. See https://hotsos.readthedocs.io/en/latest/contrib/testing.html
    for more information.
    """
