#!/usr/bin/python3
import re
import os

from common import helpers

# HOTSOS GLOBALS
VERBOSITY_LEVEL = int(os.environ.get('VERBOSITY_LEVEL', 0))
DATA_ROOT = os.environ.get('DATA_ROOT', '/')

VM_INFO = []


def get_vm_info():
    for line in helpers.get_ps():
        ret = re.compile(".+product=OpenStack Nova.+").match(line)
        if ret:
            ret = re.compile(r".+uuid\s+([a-z0-9\-]+)[\s,]+.+").match(ret[0])
            if ret:
                VM_INFO.append(ret[1])


if __name__ == "__main__":
    get_vm_info()
    if VM_INFO:
        helpers.HOTSOSYaml.dump({"instances": VM_INFO}, indent=2)
