#!/usr/bin/python3
import re
import os

from common import helpers

from openstack_common import OST_PROJECTS, OST_DEP_PKGS

# HOTSOS GLOBALS
VERBOSITY_LEVEL = int(os.environ.get('VERBOSITY_LEVEL', 0))
DATA_ROOT = os.environ.get('DATA_ROOT', '/')

DEP_LIST = OST_PROJECTS + OST_DEP_PKGS
PKG_INFO = []


def get_pkg_info():
    dpkg_l = helpers.get_dpkg_l()
    if not dpkg_l:
        return

    for line in dpkg_l:
        for dep in DEP_LIST:
            ret = re.compile(r"^ii\s+({}[0-9a-z\-]*)\s+(\S+)\s+.+"
                             .format(dep)).match(line)
            if ret:
                PKG_INFO.append("{} {}".format(ret[1], ret[2]))


if __name__ == "__main__":
    get_pkg_info()
    if PKG_INFO:
        helpers.HOTSOSYaml.dump({"dpkg": PKG_INFO}, indent=2)
