#!/bin/bash -u

((VERBOSITY_LEVEL>=3)) || exit 0

declare -a ost_projects=(
    aodh
    barbican
    ceilometer
    cinder  
    designate
    glance
    gnocchi
    heat
    horizon 
    keystone
    neutron
    nova
    octavia
    swift
)

echo -e "  dpkg:"

data_source=sos_commands/dpkg/dpkg_-l
[ -e "$data_source" ] || { echo "data source not found: $data_source"; exit 0; }

for proj in ${ost_projects[@]}; do
    readarray -t packages<<<`egrep "^ii\s+$proj" $data_source| awk '{print $2}'`
    for pkg in ${packages[@]}; do
        ver=`egrep "^ii\s+$pkg " $data_source| awk '{print $3}'`
        echo "  $INDENT_STR $pkg $ver"
    done | sort -k2 
done

