name: hotsos
adopt-info: hotsos
summary: Collect application operational information.
description:
  Software analysis toolkit. Define checks in high-level language and leverage
  library to perform analysis of common Cloud applications.
confinement: classic
grade: stable
base: core20
environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  PYTHONPATH: ${SNAP}/lib/python3.8/site-packages

# dpkg won't work without this
layout:
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP_DATA/etc/dpkg/dpkg.cfg
  /etc/dpkg/dpkg.cfg.d:
    bind: $SNAP_DATA/etc/dpkg/dpkg.cfg.d

apps:
  hotsos:
    command: bin/hotsos
parts:
  hotsos:
    plugin: python
    source: .
    build-packages:
      - git
      - python3-pip
    override-pull: |
      set -e -u -x
      snapcraftctl pull
      pip install setuptools-git-versioning
      snapcraftctl set-version "$(setuptools-git-versioning)"
    override-build: |
      set -e -u -x
      git rev-parse --short HEAD > hotsos/.repo-info
      snapcraftctl build
    stage:
     - -tests
