name: hotsos
version: '1.0'
summary: Collect application operational information.
description:
  Software analysis toolkit. Define checks in high-level
  language and leverage library to perform analysis of
  common Cloud applications.
confinement: classic
grade: stable
base: core20
architectures: [amd64, arm64]
environment:
  REPO_INFO_PATH: $SNAP/repo-info
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  PYTHONPATH: $SNAP/lib/python3.8/site-packages
  LD_PRELOAD: $SNAP/libpreload-semaphores.so

# dpkg won't work without this
layout:
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP_DATA/etc/dpkg/dpkg.cfg
  /etc/dpkg/dpkg.cfg.d:
    bind: $SNAP_DATA/etc/dpkg/dpkg.cfg.d

apps:
  hotsos:
    command: bin/hotsos
parts:
  hotsos-cli:
    plugin: dump
    source: .
    override-build: |
      rm -rf tests
      git rev-parse --short HEAD > repo-info
      snapcraftctl build
    organize:
      defs: etc/hotsos/defs
    build-packages: [git]
  hotsos:
    plugin: python
    source: .
    stage-packages: [coreutils, bsdmainutils, systemd, dpkg, python3-yaml,
                     python3-simplejson, python3-click]
    python-packages:
      - cryptography==3.4.8
      - wheel
      - pip
      - setuptools
    requirements:
      - requirements.txt
    build-environment:
      - "CRYPTOGRAPHY_DONT_BUILD_RUST": "1"
    filesets:
      # need to exclude these files since they are dangling symlinks
      # that cause the snapstore to reject the upload.
      exclude-systemd-files:
        - -lib/systemd/system/hwclock.service
        - -lib/systemd/system/rc.service
        - -lib/systemd/system/x11-common.service
        - -lib/systemd/system/cryptdisks-early.service
        - -lib/systemd/system/rcS.service
        - -lib/systemd/system/cryptdisks.service
    stage:
      - $exclude-systemd-files
  sem-open-preload:
    source: https://github.com/snapcore/snapcraft-preloads.git
    source-subdir: semaphores
    plugin: make
