name: hotsos
version: '1.0'
summary: Collect application operational information.
description:
  Collect information about specific applications and raise issues when
  problems are detected. Can be run against a host or sosreport.
  A number of application plugins are supported including Openstack, Ceph,
  Kubernetes, Juju and more. The output is a summary from each plugin and uses
  yaml format by default. By default all plugins are run and only produce ouput
  if applicable. If you  want to run specific plugins you can choose from a
  selection (--list-plugins). See --help for more options.
confinement: classic
grade: stable
base: core20
environment:
  REPO_INFO_PATH: $SNAP/repo-info
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

# dpkg won't work without this
layout:
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP_DATA/etc/dpkg/dpkg.cfg
  /etc/dpkg/dpkg.cfg.d:
    bind: $SNAP_DATA/etc/dpkg/dpkg.cfg.d

apps:
  hotsos:
    command: scripts/hotsos
    environment:
      LD_PRELOAD: "$SNAP/libpreload-semaphores.so"
parts:
  hotsos:
    source: .
    plugin: dump
    stage-packages: [coreutils, bsdmainutils, systemd, dpkg, python3-yaml,
                     python3-simplejson, python3-click]
    build-packages: [git]
    override-build: |
      git rev-parse --short HEAD > repo-info
      rm -rf tests
      snapcraftctl build
    filesets:
      # need to exclude these files since they are dangling symlinks
      # that cause the snapstore to reject the upload.
      exclude-systemd-files:
        - -lib/systemd/system/hwclock.service
        - -lib/systemd/system/rc.service
        - -lib/systemd/system/x11-common.service
        - -lib/systemd/system/cryptdisks-early.service
        - -lib/systemd/system/rcS.service
        - -lib/systemd/system/cryptdisks.service
    stage:
      - $exclude-systemd-files
  sem-open-preload:
    source: https://github.com/snapcore/snapcraft-preloads.git
    source-subdir: semaphores
    plugin: make
