name: hotsos
version: '1.0'
summary: Create a summary of a sosreport.
description:
  Sosreports contain a large amount of information about
  a host and the applications running on it. By automating
  the extraction of useful information and identification
  of errors, we reduce the time needed to get the root of
  problems. This tool creates a yaml summary of information
  extracted by a set of plugins. The output is intentionally
  application-specific, with plugins for common projects
  such as Openstack, Kubernetes and Ceph. Different views
  are supported and when found, known bugs are presented.
confinement: strict
grade: stable
base: core18
environment:
  REPO_INFO_PATH: $SNAP/repo-info
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

apps:
  hotsos:
    command: hotsos.sh
    plugs: [home, removable-media]
    environment:
      LD_PRELOAD: "$SNAP/libpreload-semaphores.so"
parts:
  hotsos:
    source: .
    plugin: dump
    stage-packages: [coreutils, bsdmainutils, jq, bc]
    build-packages: [git]
    override-build: |
      git rev-parse --short HEAD > repo-info
      snapcraftctl build
  hotsos-python:
    source: .
    plugin: python
    stage-packages: [python3-yaml, python3-simplejson]
  sem-open-preload:
    source: https://github.com/snapcore/snapcraft-preloads.git
    source-subdir: semaphores
    plugin: make
