name: hotsos
adopt-info: hotsos
summary: Collect application operational information.
description:
  Software analysis toolkit. Define checks in high-level
  language and leverage library to perform analysis of
  common Cloud applications.
confinement: strict
grade: stable
base: core22
plugs:
  shared-memory:
    private: true
environment:
  REPO_INFO_PATH: $SNAP/repo-info
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  PYTHONPATH: $SNAP/lib/python3.8/site-packages

# dpkg won't work without this
layout:
  /etc/dpkg/dpkg.cfg:
    bind-file: $SNAP_DATA/etc/dpkg/dpkg.cfg
  /etc/dpkg/dpkg.cfg.d:
    bind: $SNAP_DATA/etc/dpkg/dpkg.cfg.d

apps:
  hotsos:
    command: bin/hotsos
    plugs:
      - home
      - network
      - network-bind
parts:
  hotsos-cli:
    plugin: dump
    source: .
    override-build: |
      rm -rf tests
      git rev-parse --short HEAD > repo-info
      craftctl default
    organize:
      hotsos/defs: etc/hotsos/defs
      hotsos/templates: etc/hotsos/templates
    build-packages: [git]
  hotsos:
    plugin: python
    source: .
    build-packages:
      - python3-pip
    stage-packages:
      - bsdmainutils
      - coreutils
      - dpkg
      - systemd
    python-packages:
      - cryptography==3.4.8
      - pip
      - setuptools
      - wheel
    python-requirements:
      - requirements.txt
    build-environment:
      - "CRYPTOGRAPHY_DONT_BUILD_RUST": "1"
    override-pull: |
      craftctl default
      pip install setuptools-git-versioning
      craftctl set version="$(setuptools-git-versioning)"
