#!/bin/bash -u
# This plugin displays system-specific information. Note that this is not
# intended to supersceded information from tools like xsos.

echo "system:"
NUM_CPUS=`lscpu| grep -P '^CPU\(s\):' | awk -F' ' '{print $2}'`
uptime| sed -r "s/.+(load average)(:.+)/- \1 ($NUM_CPUS cpus)\2/g"|xargs -l -I{} echo "  {}"
echo "${INDENT_STR}rootfs: `df| egrep ' /$'`"
