name: Issues Sync
on:
  issues:
    types: [opened]
jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: 'Automation and Tooling'
          column: 'To Do'
          repo-token: ${{ secrets.PROJ_MNG }}
