name: Notifications
on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post notification (Issue)
        if: github.event_name == 'issues'
        run: |
          TITLE=$(jq -r '.issue.title' ${GITHUB_EVENT_PATH})
          URL=$(jq -r '.issue.html_url' ${GITHUB_EVENT_PATH})
          curl -i -X POST -H "Content-Type: application/json" \
            -d "{ \
              \"text\": \"New Issue: ${{ github.event.action }} '${TITLE}' at ${URL}\" \
              }" \
            ${{ secrets.WEBHOOK_URI }}
