name: Build snap
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: snapcraft
      - name: Install snap
        run: |
          sudo snap install --dangerous --classic ${{ steps.snapcraft.outputs.snap }}
      - name: Run snap (functional test)
        run: hotsos | tee output.yaml
      - name: Run snap (JSON output)
        run: hotsos --format json tests/unit/fake_data_root/openstack | tee output.json
      - name: Run snap (HTML output)
        run: hotsos --format html tests/unit/fake_data_root/openstack | tee output.html
      - name: Run snap (Markdown output)
        run: hotsos --format markdown tests/unit/fake_data_root/openstack | tee output.md
      - name: Upload snap
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: functional-test-outputs
          path: output.*

  ssl-test-on-focal:
    runs-on: ubuntu-20.04
    needs: [snap]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: snap
        with:
          name: snap
      - name: Install snap
        run: |
          sudo snap install --dangerous --classic ${{ steps.snap.outputs.download-path }}/*.snap
      - name: Install faketime
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install --yes --no-install-recommends faketime
      - name: Run snap
        run: |
          tar -xJf .github/workflows/fake_data_root/ssl-cert.xz
          faketime '2024-01-01' hotsos --openstack --format yaml ssl-cert | tee output.yaml
          grep "The following certificates will expire in less than 60 days: ssl-cert/etc/apache2/ssl/keystone/cert_10.5.1.45" output.yaml
      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: focal-ssl-test
          path: output.*

  ssl-test-on-jammy:
    runs-on: ubuntu-22.04
    needs: [snap]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: snap
        with:
          name: snap
      - name: Install snap
        run: |
          sudo snap install --dangerous --classic ${{ steps.snap.outputs.download-path }}/*.snap
      - name: Install faketime
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install --yes --no-install-recommends faketime
      - name: Run snap
        run: |
          tar -xJf .github/workflows/fake_data_root/ssl-cert.xz
          faketime '2024-01-01' hotsos --openstack --format yaml ssl-cert | tee output.yaml
          grep "The following certificates will expire in less than 60 days: ssl-cert/etc/apache2/ssl/keystone/cert_10.5.1.45" output.yaml
      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: jammy-ssl-test
          path: output.*
