name: Build snap
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: snapcore/action-build@v1
        id: snapcraft
      - name: Upload snap
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: snap-logs
          path: /home/runner/.cache/snapcraft/log/*.log

  snap-test:
    needs: [snap]
    strategy:
      matrix:
        os: [bionic, focal, jammy]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Download snap
        uses: actions/download-artifact@v3
        with:
          name: snap
      - name: Set up lxd
        uses: canonical/setup-lxd@v0.1.0
      - name: Install in ${{ matrix.os }} container
        run: |
          set -e -u -x
          dpkg -l '*docker*'
          lxc network list
          lxc network info lxdbr0
          ip --details address
          sudo sysctl -a | grep forwarding
          sudo iptables --policy FORWARD ACCEPT
          sudo iptables --list FORWARD
          pgrep -alf dnsmasq
          lxc launch --quiet ubuntu:${{ matrix.os }} ${{ matrix.os }}
          lxc config device add ${{ matrix.os }} pwd disk source=${PWD} path=/pwd
          declare -i network_is_working=0
          for i in $(seq 10); do
            echo "${i}: testing network connectivity in container"
            lxc exec ${{ matrix.os }} -- ip --details address
            ip --details address
            ip route get 1.1.1.1
            if lxc exec ${{ matrix.os }} -- ping -q -c 1 1.1.1.1; then
              network_is_working=1
              break
            fi
            sleep 1
          done
          if (( network_is_working != 1 )); then
            echo "container failed to get a network"
            exit 1
          fi
          lxc exec ${{ matrix.os }} -- bash -c 'DEBIAN_FRONTEND=noninteractive apt-get update'
          lxc exec ${{ matrix.os }} -- bash -c 'DEBIAN_FRONTEND=noninteractive apt-get purge --yes --autoremove snapd'
          lxc exec ${{ matrix.os }} -- bash -c 'DEBIAN_FRONTEND=noninteractive apt-get install --yes snapd'
          lxc exec ${{ matrix.os }} -- snap list
          lxc exec ${{ matrix.os }} -- snap install --dangerous --classic /pwd/hotsos_*snap
          lxc exec ${{ matrix.os }} -- hotsos --version
      - name: Run snap on ${{ matrix.os }} (functional test)
        run: sudo lxc exec ${{ matrix.os }} -- hotsos > output-${{ matrix.os }}.yaml
      - name: Run snap on ${{ matrix.os }} (JSON output)
        run: sudo lxc exec ${{ matrix.os }} -- hotsos --format json tests/unit/fake_data_root/openstack > output-${{ matrix.os }}.json
      - name: Run snap on ${{ matrix.os }} (HTML output)
        run: sudo lxc exec ${{ matrix.os }} -- hotsos --format html tests/unit/fake_data_root/openstack > output-${{ matrix.os }}.html
      - name: Run snap on ${{ matrix.os }} (Markdown output)
        run: sudo lxc exec ${{ matrix.os }} -- hotsos --format markdown tests/unit/fake_data_root/openstack > output-${{ matrix.os }}.md
      - name: Upload outputs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: functional-test-outputs-${{ matrix.os }}
          path: output.*
